name: ai-pallet-piler
services:
  front-end-web:
    container_name: front-end-web
    build: ../front-end-web

    ports:
      - "5173:5173"
    
    volumes:
      - ./../front-end-web:/app
      - /app/node_modules
    

  front-end-App:
    container_name: front-end-App
    build: ../front-end-App
    depends_on:
      - backend

  backend:
    container_name: backend
    build: ../backend
    environment:
      - DATABASE_URL=${DATABASE_URL}

    ports:
      - "8000:8000"

    volumes:
      - ./../backend:/app

    depends_on:
      - database


  api-gateway:
    container_name: api-gateway
    build: ../api-gateway
    env_file:
      - ../api-gateway/.env
    ports:
      - "8080:8080"

  security-api:
    container_name: security-api
    build: ../security-api
    env_file:
      - ../security-api/.env
    ports:
      - "8090:8090"
    
  database:
    container_name: postgres-database
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: always

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always